version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "5001:5000"           # 호스트 포트를 5001로 변경
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - trading-network
    restart: unless-stopped

  quant:
    build: ./trading_quant
    ports:
      - "8888:8888"
    volumes:
      - ./trading_quant:/trading_quant
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - trading-network
    restart: unless-stopped

networks:
  trading-network:
    driver: bridge
